id: A4948ADF9
title: '7909'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - mon
  - bo
  - sa
  - zh
  datatype: PlainText
  created_at: 2022-06-28 20:17:04.230041
  last_modified_at: 2022-06-28 20:17:04.230049
