id: A4948ADF9
title: C441
type: translation
source_metadata:
  languages:
  - en
  - fr
  - mon
  - bo
  - sa
  - zh
  datatype: PlainText
  created_at: 2022-06-28 20:17:04.335207
  last_modified_at: 2022-06-28 20:17:04.335213
